### PR TITLE
Make more better

### PR DESCRIPTION
**Pull request by sethbrasile**
Separated process into distinct download script and installation script, both meant to be run either on-demand or as a monitor. Only meant to be used on Windows 10 machines. We will adapt for other OSes if necessary. This greatly reduces complexity.

1. In the case of home/pro (non-enterprise), autodetect correct ISO for requested build and download directly from Microsoft. Enterprise versions still require manual hosting
2. Will not take action if requested upgrade doesn't make sense. Will not download if 20H2 is requested and 20H2 or greater is already installed. Will not upgrade if run on non-windows 10 OS
3. Should (untested) suspend download on metered connection, and resume on non-metered connection, is adjustable in script via `BitsTransfer` `TransferPolicy`
4. Uses hash checks in both download and installation scripts to ensure ISO file integrity. Hashes are stored statically in script because Microsoft provides no method for hash retrieval, and also for the sake of security.
5. Installation script can run at any time, and will wait until ISO exists and hash matches before taking any action
6. Download script can run at any time and will check on status of download and take action if necessary
7. Will resume download after sleep, reboot, poweroff, or no connection
8. Handles most download error states, starting over from beginning if unrecoverable
9. Will install and reboot if no user logged in
10. Will install silently and not interrupt user if user is logged in
11. User logon status is checked both before installation and after. Before to decide on installation priority, if user logged in, installation runs with low priority, and after to assess whether machine should reboot
12. Saves installation logs and also caches exit message in registry upon error
13. Once installation has completed and OS is now same as requested OS, download script will delete the ISO.
14. Should theoretically work for any build of win10, just change `$automateWin10Build` to whatever build (i.e. '20H2') you want, and add appropriate acceptable hashes to script

### CODE REVIEW

**Comment by sethbrasile** [comment]
I should probably toss an "if on battery power, exit script and check back later" check right before installation in the install script

**Comment by sethbrasile** [comment]
Did that

**Comment by wmmatt** [comment]
> I should probably toss an "if on battery power, exit script and check back later" check right before installation in the install script

We should probably make it a function or some kind of practice in general to check battery status for most all scripts. In general, I think there's quite a bit we don't want to run IF on battery. Don't think that thought changes anything for this one, but just something to keep in mind.

**Review by wmmatt — APPROVED** [review]
Simple expected change, good to go

**Pull request merged**
